module.exports = (sequelize, type) => {
	return sequelize.define(
		"hoome_dossier_bancaire",
		{
			project_course_id: {
				type: type.INTEGER,
				primaryKey: true,
				autoIncrement: true,
			},
			p_1_1: { type: type.TEXT, defaultValue: "" },
			p_1_2_1: { type: type.TEXT, defaultValue: "" },
			p_1_2_2: { type: type.TEXT, defaultValue: "" },
			p_1_2_3: { type: type.TEXT, defaultValue: "" },
			p_1_3: { type: type.TEXT, defaultValue: "" },
			p_1_4: { type: type.TEXT, defaultValue: "" },
			p_1_5: { type: type.TEXT, defaultValue: "" },
			p_1_6_1: { type: type.TEXT, defaultValue: "" },
			p_1_6_2: { type: type.TEXT, defaultValue: "" },
			p_1_7: { type: type.TEXT, defaultValue: "" },
			p_1_8: { type: type.TEXT, defaultValue: "" },
			p_1_9: { type: type.TEXT, defaultValue: "" },
			p_1_10: { type: type.TEXT, defaultValue: "" },
			p_1_11: { type: type.TEXT, defaultValue: "" },
			p_1_12_1: { type: type.TEXT, defaultValue: "" },
			p_1_12_2: { type: type.TEXT, defaultValue: "" },
			p_1_12_3: { type: type.TEXT, defaultValue: "" },
			p_1_13: { type: type.TEXT, defaultValue: "" },
			p_1_13: { type: type.TEXT, defaultValue: "" },
			p_2_1: { type: type.TEXT, defaultValue: "" },
			p_2_2_1_1: { type: type.TEXT, defaultValue: "" },
			p_2_2_1_2: { type: type.TEXT, defaultValue: "" },
			p_2_2_1_3: { type: type.TEXT, defaultValue: "" },
			p_2_2_2: { type: type.TEXT, defaultValue: "" },
			p_2_2_3: { type: type.TEXT, defaultValue: "" },
			p_2_1_1: { type: type.TEXT, defaultValue: "" },
			p_2_1_2: { type: type.TEXT, defaultValue: "" },
			p_2_1_3: { type: type.TEXT, defaultValue: "" },
			p_2_1_4: { type: type.TEXT, defaultValue: "" },
			p_2_3: { type: type.TEXT, defaultValue: "" },
			p_2_4_1: { type: type.TEXT, defaultValue: "" },
			p_2_4_2: { type: type.TEXT, defaultValue: "" },
			p_2_4_3: { type: type.TEXT, defaultValue: "" },
			p_2_5: { type: type.TEXT, defaultValue: "" },
			p_2_3_co: { type: type.TEXT, defaultValue: "" },
			p_2_4_1_co: { type: type.TEXT, defaultValue: "" },
			p_2_4_2_co: { type: type.TEXT, defaultValue: "" },
			p_2_4_3_co: { type: type.TEXT, defaultValue: "" },
			p_2_5_co: { type: type.TEXT, defaultValue: "" },
			p_2_6: { type: type.TEXT, defaultValue: "" },
			p_2_7: { type: type.TEXT, defaultValue: "" },
			p_2_6_co: { type: type.TEXT, defaultValue: "" },
			p_2_7_co: { type: type.TEXT, defaultValue: "" },
			p_2_8: { type: type.TEXT, defaultValue: "" },
			p_2_9_1: { type: type.TEXT, defaultValue: "" },
			p_2_9_2: { type: type.TEXT, defaultValue: "" },
			p_2_10: { type: type.TEXT, defaultValue: "" },
			p_2_11: { type: type.TEXT, defaultValue: "" },
			p_2_12: { type: type.TEXT, defaultValue: "" },
			p_2_13: { type: type.TEXT, defaultValue: "" },
			p_3_1: { type: type.TEXT, defaultValue: "" },
			p_3_2: { type: type.TEXT, defaultValue: "" },
			p_3_3: { type: type.TEXT, defaultValue: "" },
			p_3_4: { type: type.TEXT, defaultValue: "" },
			p_3_5: { type: type.TEXT, defaultValue: "" },
			p_3_6: { type: type.TEXT, defaultValue: "" },
			p_3_7: { type: type.TEXT, defaultValue: "" },
			p_3_8: { type: type.TEXT, defaultValue: "" },
			p_3_1_co: { type: type.TEXT, defaultValue: "" },
			p_3_2_co: { type: type.TEXT, defaultValue: "" },
			p_3_3_co: { type: type.TEXT, defaultValue: "" },
			p_3_4_co: { type: type.TEXT, defaultValue: "" },
			p_3_7_co: { type: type.TEXT, defaultValue: "" },
			p_3_8_co: { type: type.TEXT, defaultValue: "" },
			p_3_9: { type: type.TEXT, defaultValue: "" },
			p_3_10_1: { type: type.TEXT, defaultValue: "" },
			p_3_10_2: { type: type.TEXT, defaultValue: "" },
			p_3_11: { type: type.TEXT, defaultValue: "" },
            p_3_12: { type: type.TEXT, defaultValue: "" },
            id_acl: { type: type.INTEGER },
            collaborators: { type: type.TEXT, defaultValue: "" },
            remarques: { type: type.TEXT, defaultValue: "" }
		},
		{ freezeTableName: true, timestamps: false }
	);
};
