export interface MandateUndersigned {
  id?: number
  ref?: string
  type_mandate?: string
  first_name?: string
  last_name?: string
  gender?: string
  date_birth?: Date
  place_birth?: string
  department?: string
  nationality?: string
  email?: string
  address?: string
  city?: string
  postal_code?: string
  country?: string
  personnal_phone?: string
  home_phone?: string
  society_name?: string
  legal_status?: string
  society_capital?: string
  society_id_number?: string
  society_rcs: string
  person_representing: string
  avi_first_name?: string
  avi_last_name?: string
  avi_lawyer_office?: string
  avi_toque?: string
  avi_email?: string
  avi_address?: string
  avi_city?: string
  avi_postal_code?: string
  avi_country?: string
  avi_personnal_phone?: string
  avi_home_phone?: string
  avi_declaration_date?: Date
  avi_society_name?: string
  avi_legal_status?: string
  avi_rcs?: string
  avi_id_number?: string
}
