export interface MandateUndersigned {
  id?: number
  ref?: string
  type_mandate?: string
  first_name?: string
  last_name?: string
  gender?: string
  date_birth?: Date
  place_birth?: string
  department?: string
  nationality?: string
  email?: string
  address?: string
  city?: string
  postal_code?: string
  country?: string
  personnal_phone?: string
  home_phone?: string
  society_name?: string
  legal_status?: string
  society_capital?: string
  society_id_number?: string
  society_rcs: string
  person_representing: string
  avi_first_name?: string
  avi_last_name?: string
  avi_lawyer_office?: string
  avi_toque?: string
  avi_email?: string
  avi_address?: string
  avi_city?: string
  avi_postal_code?: string
  avi_country?: string
  avi_personnal_phone?: string
  avi_home_phone?: string
  avi_declaration_date?: Date
  avi_society_name?: string
  avi_legal_status?: string
  avi_society_capital?: string
  avi_rcs?: string
  avi_id_number?: string
  object_cession?: string
  building_place?: string
  building_address?: string
  building_city?: string
  building_postal_code?: string
  building_country?: string
  building_name?: string
  building_area?: number
  building_description?: string
  building_lot?: string
  net_price?: number
  net_price_text?: string
  condition?: string
  margin_negociation?: number | number
  honorary_ht?: number
  honorary_ht_text?: string
  honorary_ttc?: number
  honorary_ttc_text?: string
  honorary_modality?: string
  additional_percent_ht?: number
  additional_percent_ht_text?: string
  additional_percent_ttc?: number
  additional_percent_ttc_text?: string
  additional_amount_ht?: number
  additional_amount_ht_text?: string
  additional_amount_ttc?: number
  additional_amount_ttc_text?: string
  additional_hour_type?: string
}
