import { Role } from './role';
export interface UserAcl {
  user_acl_ID?: number
  email?: string
  password?: string
  salary?: number
  birthday?: Date
  resident_french?: string
  carte_sejour?: string
  datesejour?: Date
  date_mariage?: Date
  civilite?: string
  lastname?: string
  firstname?: string
  phone_number?: string
  address?: string
  fonction?: string
  loyer?: number
  situation_familiale?: string
  train_de_vie?: string
  income?: number
  enfants?: number
  profile_pic?: string
  postal_code?: string
  city?: string
  nationalite?: string
  ages_enfants?: string
  nb_enfants_charges?: number
  logement?: string
  pays?: string
  employeur?: string
  type_contrat?: string
  prive?: boolean
  publique?: boolean
  anciennete?: string
  banque?: string
  banque_sollicite?: string
  credit_encours?: string
  patrimoine?: string
  courtier_sollicite?: string
  simulation?: string
  bnc_bic_2019?: string
  bnc_bic_2018?: string
  ADG_ID?: number
  ADA_ID?: number
  ADM_ID?: number
  CEC_ID?: number
  CBI_ID?: number
  PAR_ID?: number
  ADV_ID?: number
  ACL_ID?: number
  note_privees?: string
  progression?: number
  account_state?: boolean
  toque_number?: string
  hoomeRoleUserRoleID?: number
  hoome_role_user: Role
}
